library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity cla2 is
	port
	(
		x		:	in	std_logic_vector(1 downto 0);
		y		:	in	std_logic_vector(1 downto 0);
		cin		:	in	std_logic;
		
		s		:	out	std_logic_vector(1 downto 0);
		cout 	:	out	std_logic;		--	only needed to test if cla2 works, cout will be generated by cgen2
		BP		:	out	std_logic;		--	block propagate
		BG		:	out	std_logic		--	block generate
	);
end cla2;

architecture BHV of cla2 is

signal bg_temp	:	std_logic;
signal bp_temp	:	std_logic;
signal c1		:	std_logic;

begin
	
	bg_temp <= (x(1) and y(1)) or ((x(1) or y(1)) and (x(0) and y(0)));
	bp_temp <= (x(1) or y(1)) and (x(0) or y(0));
	c1 <= (x(0) and y(0)) or (x(0) and cin) or (y(0) and cin);
	
	
	s(0) <= x(0) xor y(0) xor cin;
	s(1) <= x(1) xor y(1) xor c1;
	cout <= bg_temp or (bp_temp and c1);
	
	BG <= bg_temp;
	BP <= bp_temp;
	
end BHV;